{% set name = "jupytext" %}
{% set version = "1.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d09f8099394d3b96f604f2b64287a6bb4b9cd701bf6aa5d62bebdd39c6e88cce

build:
  number: 0
  entry_points:
    - jupytext = jupytext.cli:jupytext
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vvv"

requirements:
  host:
    - pip
    - python
  run:
    - mock
    - nbformat >=4.0.0
    - pyyaml
    - testfixtures

test:
  imports:
    - jupytext
  commands:
    - jupytext --help

about:
  home: https://github.com/mwouts/jupytext
  doc_url: https://github.com/mwouts/jupytext/blob/master/README.md
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebooks as Markdown documents, Julia, Python or R scripts
  description: |
    Represent Jupyter notebooks as Markdown documents or Julia, Python or R scripts. Convert any
    script or Markdown document to a Jupyter notebook. Round trip conversion is robust and well tested.

    Use these simpler representations to do version control and collaborate on Jupyter notebooks.
    And refactor your notebooks encoded as scripts in your favorite IDE.

    Jupytext is available directly in Jupyter Notebook and JupyterLab, and also on the command line.

extra:
  recipe-maintainers:
    - grst
    - mwouts
