{% set name = "jupytext" %}
{% set version = "0.8.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0778a58bc45b0f96bd2559b51c3e451e8e52ef041e7d9c672d8b5595f662d0ce

build:
  number: 0
  entry_points:
    - jupytext = jupytext.cli:jupytext
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  host:
    - nbformat >=4.0.0
    - pip
    - python
    - pyyaml
  run:
    - mock
    - nbformat >=4.0.0
    - python
    - pyyaml
    - testfixtures

test:
  imports:
    - jupytext
  commands:
    - jupytext --help

about:
  home: https://github.com/mwouts/jupytext
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Jupyter notebooks as Markdown documents, Julia, Python or R scripts

extra:
  recipe-maintainers:
    - grst
    - mwouts
