travis:
  secure:
    BINSTAR_TOKEN: h7RrtvmfJOVCT6d6I7Oy1MHDeRLfr5pk639PKAgtdHWm0Nbcop7CNSVZ2N1AYyop75AMgrwD0Y0uqsq5Mp6ioJwloKNmZtE/I6n0D1HRPODanr7DRyDH1GM95xLDv8YNfA6GsGvh6Rp1nUCF3/9t95cGzg6Wxg2bITqJUf05wQfwPAlaTAx+rQ/svNAK3rfS1zsYeLS15enlHGE5AotbbvwQF1p/0f7fnC22ZM0A15CGXciMY3XaZZLV06X8HE5U7ZQ9f39ImTt6JNxXf3DRTjvwAs7Qgm5UW9XvmJSu0RxJ2nIysA8ZFQHtgSIBB56OsKJGNsa9S7FqwIuuEIKpxH3Lvp1Hfr/Lz428Z8VfaB4Bhkz03VqjlLUFw3P0uzRx6PPjqZ3Lm2oYKJ4WNB+ojpSaEHqinieB08LX7qeKUgrUARcMT7Y4pRJQ+ZbaYF35lY3S1OUjk86NoacvriJSjWc1/QP8Nv8QqHUmWX9+aJ1eU0s6PQuRAo00JChqFy8LWa/2bzZ8D85qUWIlfxOUxph5vDm9AGrUhTOFngolRCUrxFhWmRqCTZ/vXcAVdc9Q21n90tyXvL6/CnRGKcColMFBx2d5GQKEdYrmslLQnpHaqxs9cqyY9fk7A6aZxu2+J1NmVK4/PGUhraUb4QbiUS+lyKILXETOP5bMFPBTtuk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
